### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by pandasoli** [pfirsich/lua-discordRPC#11]
I miss the possibility of creating buttons.

![image](https://github.com/pfirsich/lua-discordRPC/assets/76575902/a405ce3b-1918-4351-bae8-7aec9d265374)
* Image created with the plugin [vscord](https://github.com/leonardssh/vscord), that uses [discordjs](https://github.com/discordjs)

I read a bit of [discorprc](https://github.com/discord/discord-rpc) and didn't find the support for buttons.  
But I'm new in vim-discord stuff so you may know what could be done.

**Comment by pfirsich** [comment]
I had a look at the docs for a few minutes and also could not find it. Note that discord-rpc has been deprecated in favor of Discord GameSDK, so possibly this functionality is only provided by the new API. I am pretty sure that there was no functionality like this when I first made this library (6 years ago).

Also I don't use this library anymore, so I will likely not spend the time to add more features. If you manage to find out whether this functionality is provided by the new GameSDK, please let me know, so I can close this issue. If it turns out to be possible to do this with the old Discord RPC API, feel free to contribute the necessary changes. This library is really just a small wrapper, so it should be fairly easy, if the API is available.

**Comment by pandasoli** [comment]
I made a Lua lib to create an IPC connection with Discord. [pandasoli/discord-ipc](https://github.com/pandasoli/discord-ipc).  
Also, I've developed a fork of DiscordRPC that supports buttons [pandasoli/discord-rpc](https://github.com/pandasoli/discord-rpc).

**Comment by asumbek** [comment]
I made a much more updated library, which supports Lua 5.1-5.4 and LuaJIT. It also provides a wrapper for Löve.
[komothecat/lpresence](https://github.com/komothecat/lpresence)
